version: '2.4'
services:
  postgresql:
    image: postgres:11.4
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: AirbnbDB
    volumes:
      - ./database/local:/docker-entrypoint-initdb.d/
    ports:
      - 5439:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql -d postgres"]
      interval: 1s
      timeout: 1s
      retries: 5
  flyway:
    image: flyway/flyway
    command:
      -user=postgresql
      -password=postgresql
      -url=jdbc:postgresql://postgresql:5432/AirbnbDB
      -locations=filesystem:/database/scripts
      -placeholders.airbnb_db_user=airbnb_db_user
      -placeholders.airbnb_db_password=airbnb_db_password
      -baselineOnMigrate=true migrate
    volumes:
      - ./database/scripts:/database/scripts
    depends_on:
      postgresql:
        condition: service_healthy
  airbnb-app:
    build: .
    environment:
      environment: local
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 3000:8080
